name: docker-react test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file Dockerfile.dev -t eddyspaghette/docker-react

    - name: Run test suite
      run: docker run -e CI=true eddyspaghette/docker-react npm run test

